### ISSUE TITLE
Where is the source code 

### ISSUE THREAD

**Issue by keyboard-slayer** [Swartype/os-one#1]
I think you might lost it mate

**Comment by Woomymy** [comment]
The source code is in /dev/null maybe

**Comment by rdmsr** [comment]
I couldn't find it either, I think you can reproduce the system pretty easily though.
Step 1: Get Linux Lite.
Step 2: Install KDE
Step 3: Add a wallpaper
Done

**Comment by keyboard-slayer** [comment]
```
~ ❯❯❯ cat /dev/null
That's not the code you are looking for
~ ❯❯❯ 
```

**Comment by sleepy-monax** [comment]
Anyway oneOS isTM justTM betterTM

**Comment by ghost** [comment]
It’s just Ubuntu with kde in white and with custom wallpapers, so there is no source code 😉

**Comment by keyboard-slayer** [comment]
The issue is not addressed :disappointed:
